name: Update Database
on: [workflow_dispatch]

jobs:
  Update-Database:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install httpx==0.24.1 pandas==1.5.2 pymongo==4.3.3

      - name: execute python script
        env:
          MONGODB: ${{ secrets.MONGODB }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python ./src/update.py
