name: Update Database
on: [workflow_dispatch]

jobs:
  Update-Database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install h2==4.1.0 httpx==0.24.1 pandas==1.5.2 pymongo==4.3.3
      - name: Execute python script
        env:
          MONGODB: ${{ secrets.MONGODB }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python src/update.py
